set(LETINCOMP_FOUND OFF)

find_path(LETINCOMP_INCLUDE_DIR letin/comp.hpp PATHS "$ENV{HOME}/letin/include")

find_library(LETINCOMP_LIBRARY letincomp PATHS "$ENV{HOME}/letin/lib")

if(LETINCOMP_INCLUDE_DIR AND LETINCOMP_LIBRARY)
	set(LETINCOMP_FOUND ON)
	set(LETINCOMP_LIBRARIES ${LETINCOMP_LIBRARY})
else(LETINCOMP_INCLUDE_DIR AND LETINCOMP_LIBRARY)
	if(LETINCOMP_FIND_REQUIRED)
		message(FATAL_ERROR "Could not find letincomp")
	else(LETINCOMP_FIND_REQUIRED)
		message(STATUS "Could not find letincomp")
	endif(LETINCOMP_FIND_REQUIRED)
endif(LETINCOMP_INCLUDE_DIR AND LETINCOMP_LIBRARY)
